version: "3"
services:
  ca-app:
    image: netreconlab/ca-server:latest
    environment:
      - CA_SERVER_PRIVATE_KEY_FILE=./server/ca/private/cakey.pem # (Required) Location and name of private key
      - CA_SERVER_ROOT_CA_CERT=./server/ca/private/cacert.der # (Required) Location and name of CA certificate
      - CA_SERVER_DATABASE_NAME=server/dbs/appdb.sqlite # (Required) Location and name of the database
      - CA_SERVER_CA_DIRECTORY=./server/ca # Location to store CA related files
      - CA_SERVER_ROUTE_USER_PREFIX=/appusers # The prefix to add to all user related routes
      - CA_SERVER_ROUTE_CERTIFICATE_PREFIX=/certificates # The prefix to add to all certificate related routes
      - CA_SERVER_ROUNDS=5 # Number of rounds
    restart: always
    volumes:
      - ./server/ca:/app/server/ca
      - ./server/dbs:/app/server/dbs
    ports:
      - '3000:3000'
