version: "3"
services:
  ca-app:
    image: netreconlab/ca-server:0.0.1
    environment:
      - DATABASE_NAME=server/dbs/appdb.sqlite
      - RSA_PRIVATE_KEY=./server/ca/private/cakey.pem
      - ROOT_CA_CERT=./server/ca/private/cacert.der
      - ROUNDS=5
    restart: always
    volumes:
      - ./server/ca:/app/server/ca
      - ./server/dbs:/app/server/dbs
    ports:
      - '3000:3000'
